presales/urls.py
from django.conf.urls import patterns, url
from .views import QuotationCreateView, get_quotation, get_quickquotation

urlpatterns = patterns('',
	url(r'^projects/(?P<project_slug>[-\w]+)/person/(?P<person_slug>[-\w]+)/(?P<unity_slug>[-\w]+)/quotation/$', QuotationCreateView.as_view(), name='create_quotation'),
	url(r"^download/quotation/(?P<pk>[-\w]+)/$", get_quotation, name="download_quotation"),
	url(r"^download/quickquotation/(?P<pk>[-\w]+)/$", get_quickquotation, name="download_quickquotation")
)

projects/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from .views import ProjectCreateView, ProjectDetailView, ProjectListView, LandingTemplateView


urlpatterns = patterns('',
	url(r'^$', LandingTemplateView.as_view(), name='index'),
	url(r'^projects/$', ProjectListView.as_view(), name='projects'),
	url(r'^projects/create/$', ProjectCreateView.as_view(), name='project_create'),
	url(r'^projects/(?P<project_slug>[-\w]+)/$', ProjectDetailView.as_view(), name='project_detail'),
)

units/urls.py
from django.conf.urls import patterns, url
from .views import UnityTypeCreateView, UnityImport, UnityExport, UnityProcessImport, UnityListView, UnityDetailUpdateAPIView

urlpatterns = patterns('',
	url(r'^projects/(?P<project_slug>[-\w]+)/unitytypes/create$', UnityTypeCreateView.as_view(), name='unity_types_create'),
#	url(r'^projects/(?P<project_slug>[-\w]+)/unities/$', UnityListView.as_view(), name='unities_list'),
#	url(r'^projects/(?P<project_slug>[-\w]+)/unities/(?P<slug>[-\w]+)/$', UnityDetailUpdateAPIView.as_view(), name='unity_detail'),
    url(r'^projects/(?P<project_slug>[-\w]+)/import/unities/$', UnityImport.as_view(), name='unities_import'),
    url(r'^projects/(?P<project_slug>[-\w]+)/export/unities/$', UnityExport.as_view(), name='unities_export'),
    url(r'^projects/(?P<project_slug>[-\w]+)/process_import/unities/$', UnityProcessImport.as_view(), name='unities_process_import'),
)

projects/models.py
from __future__ import unicode_literals
import random
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.template import defaultfilters
from hashlib import sha1
from sesamo.tasks import SendEmail

class Project(models.Model):
	name = models.CharField(max_length=100)
	booking_price = models.IntegerField()
	initial_fee_percentage = models.IntegerField()
	slug = models.CharField(max_length=100)

	def save(self, *args, **kwargs):
		if not self.pk:
			self.slug = defaultfilters.slugify(self.name)
			print (self.slug)
			try:
				project_exists = Project.objects.get(slug__iexact=self.slug)
				if project_exists:
					self.slug = "{0}-{1}".format(self.slug, sha1(str(random.random()).encode('utf-8')).hexdigest()[:5])
			except Project.DoesNotExist:
				super(Project, self).save(*args, **kwargs)

	def __str__(self, *args, **kwargs):
		return self.name

	def get_absolute_url(self):
		return reverse('project_detail', kwargs={'project_slug': self.slug})

class ProjectTeam(models.Model):
	project = models.OneToOneField(Project)
	users = models.ManyToManyField(settings.AUTH_PROFILE_MODULE)

	def __str__(self):
		return self.project.name


class ProjectSettings(models.Model):
	booking_price = models.IntegerField()
	initial_fee_percentage = models.IntegerField()
	project = models.OneToOneField(Project, related_name="settings")

	def __str__(self):
		return "Settings of {}".format(self.project.name)

presales/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Quotation

class IntegerCurrencyInput(forms.TextInput):
    def render(self, name, value, attrs=None):
        from django.contrib.humanize.templatetags.humanize import intcomma
        if value:
            value = "$%s" % intcomma(value)
        return super(IntegerCurrencyInput, self).render(name, value, attrs)

class IntegerCurrencyField(forms.IntegerField):
    widget = IntegerCurrencyInput
    
    def clean(self, value):
        if value:
            if value[0] == "$": value = value[1:] # Cut off the dollar sign
            value = value.replace('.', '') # Remove Commas
        print (value)
        value = super(IntegerCurrencyField, self).clean(value)
        return int(value) if value else value


class QuotationModelForm(forms.ModelForm):
	subsidy = IntegerCurrencyField()
	savings = IntegerCurrencyField()
	severance = IntegerCurrencyField()
	monthly_income = IntegerCurrencyField()
	others = IntegerCurrencyField()

	class Meta:
		model = Quotation
		fields = [
			"subsidy",
			"savings",
			"severance",
			"months_to_deliver",
			"monthly_income", 
			"others"
		]

presales/views.py
from datetime import datetime
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from rest_framework import generics, filters
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.views import APIView
from .models import Quotation, QuickQuotation, VirtualBooking
from .forms import QuotationModelForm
from .serializers import QuotationSerializer, QuickQuotationSerializer, VirtualBookingSerializer, VirtualBookingSerializerWithPersonSerializer
from .filters import PersonFilter
from django.template import RequestContext
from django.template.loader import get_template

from sesamo.mixins import SlugManagerMixin

from weasyprint import HTML, CSS

from persons.models import Person
from persons.serializers import PersonSmallSerializer

@method_decorator(login_required, name='dispatch')
class VirtualBookingCreateView(generics.CreateAPIView):
    queryset = VirtualBooking.objects.all()
    serializer_class = VirtualBookingSerializer

@method_decorator(login_required, name='dispatch')
class VirtualBookingForUnityListAPIView(SlugManagerMixin, generics.ListAPIView):
	model_class = VirtualBooking
	serializer_class = VirtualBookingSerializerWithPersonSerializer

	def get_queryset(self):
		project = self.get_project()
		unity = self.kwargs.get("id")
		virtual_bookings = VirtualBooking.objects.filter(unity=unity, closed=False)
		return virtual_bookings

@method_decorator(login_required, name='dispatch')
class PersonSearchView(SlugManagerMixin, generics.ListAPIView):
    model_class = Person
    queryset = Person.objects.all()
    serializer_class = PersonSmallSerializer
    filter_backends = (filters.SearchFilter, DjangoFilterBackend)
    filter_class = PersonFilter
    search_fields = ("^first_name", "^last_name")

    def get_queryset(self):
        project = self.get_project()
        persons_in_project = Person.objects.filter(project=project)
        return persons_in_project

@method_decorator(login_required, name='dispatch')
class QuotationCreateView(SlugManagerMixin, CreateView):
	model = Quotation
	form_class = QuotationModelForm

	def form_valid(self, form):
		person = self.get_person()
		project = self.get_project()
		unity = self.get_unity()
		self.object = form.save(commit=False)
		self.object.person = person
		self.object.unity = unity
		self.object.save()
		super(QuotationCreateView, self).form_valid(form)
		return HttpResponseRedirect(reverse("person_tracking", kwargs={"project_slug": project.slug, "person_slug": person.slug}))

	def get_success_url(self):
		project = self.get_project()
		person = self.get_person()
		return reverse("person_tracking", kwargs={"project_slug": project.slug, "person_slug": person.slug})

def get_quotation(request, pk):
	html_template = get_template("presales/quotation_template.html")
	quotation = get_object_or_404(Quotation, pk=pk)
	booking_price_for_this_quotation = quotation.unity.project.booking_price
	thirty_percent = int(0.3 * int(quotation.unity.price))
	credit_to_request = int(int(quotation.unity.price) - thirty_percent)
	initial_fee_residue = thirty_percent - (int(quotation.savings) + int(booking_price_for_this_quotation) + int(quotation.severance) + int(quotation.subsidy) + int(quotation.others))
	monthly_fees = int(int(initial_fee_residue) / int(quotation.months_to_deliver))
	today = str(datetime.today().date())
	data_dict = {
		'pagesize':"A4",
		'title': 'Cotizacion de Apartamento {0}'.format(quotation.unity.name),
		'apartment': quotation.unity.name,
		'apartment_price': int(quotation.unity.price),
		'thirty_percent': thirty_percent,
		'booking_price': booking_price_for_this_quotation,
		'savings': int(quotation.savings),
		'severance': int(quotation.severance),
		'subsidy': int(quotation.subsidy),
		'initial_fee_residue': initial_fee_residue,
		'monthly_fees': monthly_fees,
		'months_to_deliver': quotation.months_to_deliver,
		'credit_to_request': credit_to_request,
		'today': today,
		'unity': quotation.unity,
		'others': quotation.others
	}

	rendered_html = html_template.render(RequestContext(request, data_dict)).encode(encoding="UTF-8")

	pdf_file = HTML(string=rendered_html).write_pdf(stylesheets=[CSS(settings.STATIC_ROOT + "/css/quotation.css")])

	http_response = HttpResponse(pdf_file, content_type='application/pdf')
	http_response['Content-Disposition'] = 'filename="cotizacion.pdf"'
	return http_response

@method_decorator(login_required, name='dispatch')
class QuotationCreateAPIView(generics.CreateAPIView):
	queryset = Quotation.objects.all()
	serializer_class = QuotationSerializer

	def get_serializer_context(self):
		return {
			'request': self.request,
			'format': self.format_kwarg,
			'view': self
		}

@method_decorator(login_required, name='dispatch')
class QuickQuotationCreateAPIView(generics.CreateAPIView):
	queryset = QuickQuotation.objects.all()
	serializer_class = QuickQuotationSerializer

	def get_serializer_context(self):
		return {
			'request': self.request,
			'format': self.format_kwarg,
			'view': self
		}

#QUICK-QUOTATIONS

def get_quickquotation(request, pk):
	html_template = get_template("presales/quickquotation_template.html")
	quickquotation = get_object_or_404(QuickQuotation, pk=pk)
	booking_price_for_this_quotation = quickquotation.unity.project.booking_price
	thirty_percent = int(0.3 * int(quickquotation.unity.price))
	credit_to_request = int(int(quickquotation.unity.price) - thirty_percent)
	initial_fee_residue = thirty_percent - (int(quickquotation.savings) + int(booking_price_for_this_quotation))
	monthly_fees = int(int(initial_fee_residue) / int(quickquotation.months_to_deliver))
	today = str(datetime.today().date())
	data_dict = {
		'pagesize':"A4",
		'title': 'Cotizacion de Apartamento {0}'.format(quickquotation.unity.name),
		'apartment': quickquotation.unity.name,
		'apartment_price': int(quickquotation.unity.price),
		'thirty_percent': thirty_percent,
		'booking_price': booking_price_for_this_quotation,
		'savings': int(quickquotation.savings),
		'initial_fee_residue': initial_fee_residue,
		'monthly_fees': monthly_fees,
		'months_to_deliver': quickquotation.months_to_deliver,
		'credit_to_request': credit_to_request,
		'today': today,
		'unity': quickquotation.unity,
	}

	rendered_html = html_template.render(RequestContext(request, data_dict)).encode(encoding="UTF-8")

	pdf_file = HTML(string=rendered_html).write_pdf(stylesheets=[CSS(settings.STATIC_ROOT + "/css/quotation.css")])

	http_response = HttpResponse(pdf_file, content_type='application/pdf')
	http_response['Content-Disposition'] = 'filename="cotizacion.pdf"'
	return http_response


class SendNotificationView(SlugManagerMixin, APIView):
	def post(self, request, *args, **kwargs):
		project = self.get_project()
		report_serializer = ReportSerializer(data=request.data)
		if report_serializer.is_valid():
			unities_ids = notification_serializer.data["unities"]
			html_snippet = notification_serializer.data["html_snippet"]
			tower_number = notification_serializer.data["tower_number"]
			request_user_id = request.user.id
			project_id = project.id
			task = SendNotificationsTask.delay(request_user_id, project_id, unities_ids, html_snippet, tower_number)
			data = {"task_id":task.id}
			return Response(data=data, status=status.HTTP_200_OK)
		else:
			return Response(status= status.HTTP_400_BAD_REQUEST)

projects/views.py
from rest_framework import generics
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, RedirectView, ListView, TemplateView
from datetime import datetime
from sesamo.decorators import user_belongs_to_project
from sesamo.mixins import SlugManagerMixin
from .models import Project, ProjectTeam, ProjectSettings
from .permissions import IsManagerAndIsOnTeamOrForbidden, IsOnTeamOrForbidden
from .serializers import ProjectSettingsSerializer, ProjectSerializer

from rest_framework import viewsets
from rest_framework.response import Response

decorators = [login_required, user_belongs_to_project]

@method_decorator(login_required, name='dispatch')
class ProjectCreateView(CreateView):
	model = Project
	fields = ["name", "booking_price", "initial_fee_percentage"]
	template_name = "projects/create_first_project.html"

	def form_valid(self, form):
		self.object = form.save()
		try:
			project_team = ProjectTeam.objects.create(project=self.object)
			project_team.users.add(self.request.user.user_profile)
			project_team.save()
		except Exception as err:
			print (err)
		return super(ProjectCreateView, self).form_valid(form)


@method_decorator(decorators, name='dispatch')
class ProjectDetailView(DetailView):
	model = Project
	slug_url_kwarg = 'project_slug'
	queryset = Project.objects.all()

	def get(self, request, *args, **kwargs):
		self.object = self.get_object()
		redirect_kwargs = {'project_slug': self.object.slug}
		print (request.user.user_profile.user_type)
		if not self.object.unity_set.all():
			return redirect(reverse('unity_types_create', kwargs=redirect_kwargs))
			#context = self.get_context_data(object=self.object)
			#return self.render_to_response(context)
		if request.user.user_profile.user_type == "vendedor" or request.user.user_profile.user_type == "gerente" or request.user.user_profile.user_type == "empleado" :
			return redirect(reverse('presale_splash', kwargs=redirect_kwargs))
		elif request.user.user_profile.user_type == "soporte":
			return redirect(reverse('office_splash', kwargs=redirect_kwargs))
		#elif request.user.user_profile.user_type == "gerente":
		#	return redirect(reverse())

@method_decorator(login_required, name='dispatch')
class ProjectListView(ListView):
	context_object_name = "projects"
	model = Project
	template_name = "projects/projects_list.html"

	def get_queryset(self):
		profile = self.request.user.user_profile
		projects = [project_team.project for project_team in profile.projectteam_set.all()]
		return projects

	def get(self, request, *args, **kwargs):
		self.object_list = self.get_queryset()
		if not self.object_list:
			return redirect(reverse("project_create"))
		context = self.get_context_data()
		return self.render_to_response(context)


class ProjectSettingsViewSet(SlugManagerMixin, viewsets.ModelViewSet):
	model_class = ProjectSettings
	serializer_class = ProjectSettingsSerializer
	queryset = ProjectSettings.objects.all()
	lookup_field = "project__slug"
	lookup_url_kwarg = "project_slug"

	def get_permissions(self):
		if self.request.method == 'GET':
			self.permission_classes = [IsOnTeamOrForbidden,]
		elif self.request.method == 'PUT' or self.request.method == "POST":
			self.permission_classes = [IsManagerAndIsOnTeamOrForbidden,]
		return super(ProjectSettingsViewSet, self).get_permissions()

#class ProjectSettingsViewSet(viewsets.ViewSet):
#	def retrieve(self, request, *args, **kwargs):
#		project_slug = kwargs["project_slug"]
#		project = get_object_or_404(Project, slug__iexact=project_slug)
#		project_settings = project.settings
#		serializer = ProjectSettingsSerializer(project_settings, initial={"booking_price":project.booking_price})
#		return Response(serializer.data)

#	def create(self, request, *args, **kwargs):
#		project_slug = kwargs["project_slug"]
#		project = get_object_or_404(Project, slug__iexact=project_slug)
#		serializer = ProjectSettingsSerializer(initial={"booking_price":project.booking_price})
#		return Response(serializer.data)




class ProjectRetrieveAPIView(generics.RetrieveAPIView):
	model_class = Project
	queryset = Project.objects.all()
	serializer_class = ProjectSerializer
	lookup_field = "slug"
	lookup_url_kwarg = "project_slug"


#class ProjectTeamRetrieveAPIView(generics.RetrieveAPIView):
#	model_class = ProjectTeam
#	queryset = ProjectTeam.objects.all()
#	serializer_class = ProjectTeamSerializer
#	lookup_field = "project__slug"
#	lookup_url_kwarg = "project_slug"

class LandingTemplateView(TemplateView):
	template_name = "landing.html"

templates/projects/create_first_project.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}
	Crea tu primer proyecto
{% endblock %}
{% block main-container %}
	<section id="main-container">
		<div class="container">
			<div class="row">
				<div class="col s12 welcome-title-wrapper hide-on-small-only">
					<h1 class="welcome-title center">Hola {{ request.user.get_full_name }}. Bienvenida a Sesamo de PCG Constructora</h1>
				</div>
				<div class="col s12 center">
					<div class="row">
				        <div class="col s12 m6 l4 push-m3 push-l4 creation-box-wrapper">
				          <div style="height:460px" class="card medium">
				          	<!--<i class="material-icons add-project-icon">add_circle_outline</i>-->
				          	<img src="{% static "img/building.png" %}" style="margin-top: 5%;">
				          	<div class="card-content" style="font-size: 18px; font-weight: bold; color: #6c7383;">
				              <p>Aún no tienes ningun proyecto. Empieza por crear uno nuevo</p>
				           	</div>
				           	<form method="POST" id="create-project-form">
				           	{% csrf_token %}
					           	<div class="row">
					           			<!--Hardcoded form for Django CreateView-->
		        						<div class="input-field col s12 m8 l8 offset-l2">
		        							<input id="id_name" maxlength="100" name="name" type="text"/>
		        							<label for="id_name" style="text-align: left;">Nombre del proyecto:</label>
		        						</div>

		        						<div class="input-field col s12 m8 l8 offset-l2">
		        							<input id="id_booking_price" name="booking_price" type="number" />
		        							<label for="id_name" style="text-align: left;">Precio de separación:</label>
		        						</div>

	      						</div>
					           	<a href="javascript:$('#create-project-form').submit();" class="waves-effect waves-light btn custom-btn"><i class="material-icons left" style="font-weight: bold;">add</i>Crear proyecto</a>
					        </form>
				          </div>
				        </div>
      				</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/projects/presales.html
{% extends "base_app.html" %}
{% block main-container %}
<div class="search-bar">
	<span><i class="fa fa-search" aria-hidden="true"></i> </span><input type="text" id="search" placeholder="Buscar Persona" />
</div>
<div class="sort-blocks">

	<div class="state ">
		<div class="state-tit">Altamente Probable <span>+</span></div>
		<div class="state-content">
			<div class="card-info" draggable="true">
				<div class="initials green">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials violet">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials yellow">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials blue">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
		</div>
	</div>

	<div class="state ">
		<div class="state-tit">Medianamente Probable <span>+</span></div>
		<div class="state-content">
			<div class="card-info" draggable="true">
				<div class="initials green">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials violet">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials yellow">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials blue">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
		</div>
	</div>

	<div class="state ">
		<div class="state-tit">Poco Probable <span>+</span></div>
		<div class="state-content">
			<div class="card-info" draggable="true">
				<div class="initials green">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials violet">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials yellow">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
			<div class="card-info" draggable="true">
				<div class="initials blue">VA</div>
				<div class="info">
					<h3>Victor Aguirre</h3>
					<p>320987654</p>
					<small>Últ.	Interacción hace 3 dias</small>
				</div>
			</div>
		</div>
	</div>

</div>
{% endblock %}

templates/projects/project_detail.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{{project}}
</body>
</html>

templates/projects/projects_list.html
{% extends "base.html" %}
{% block main-container %}
	<section id="main-container" class="projectsList">
		<h1>¿A qué proyecto quieres ingresar?</h1>
		<div class="projectsList-container">
			<div class="projectsList-header">
				<h4>Mis proyectos</h4>
				<span>1 Proyecto</span>
			</div>
			<div class="projectsList-projects">
				<ul>
					{% for project in projects %}
						<li>
							<span class="projectsList-colorBar"></span>
							<div class="projectsList-project">{{project}}</div>
							<a href="{% url "project_detail" project.slug %}">Entrar</a>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>

	</section>
{% endblock %}