persons/urls.py
from django.conf.urls import patterns, url
from .views import PersonCreateView, PersonDetailView, PersonDetailUpdateView, PreSaleInitialView, PersonListAPIView, OfficeInitialView, PersonExport, PersonImport
#PersonListView

urlpatterns = patterns('',
	url(r'^projects/(?P<project_slug>[-\w]+)/person/create/$', PersonCreateView.as_view(), name='create_person'),
	url(r'^projects/(?P<project_slug>[-\w]+)/presale/#/segmentation/persona/(?P<person_slug>[-\w]+)/$', PersonDetailView.as_view(), name='person_tracking'),
	url(r'^projects/(?P<project_slug>[-\w]+)/presale/$', PreSaleInitialView.as_view(), name='presale_splash'),
	#Office Splash is the url for those users who are not salespeople
	url(r'^projects/(?P<project_slug>[-\w]+)/office/$', OfficeInitialView.as_view(), name='office_splash'),
	url(r'^projects/(?P<project_slug>[-\w]+)/import/persons/$', PersonImport.as_view(), name='unities_import'),
    url(r'^projects/(?P<project_slug>[-\w]+)/export/persons/$', PersonExport.as_view(), name='unities_export'),
	#url(r'^projects/(?P<project_slug>[-\w]+)/segmentation/$', PersonListView.as_view(), name='segmentation'),
)

units/urls.py
from django.conf.urls import patterns, url
from .views import UnityTypeCreateView, UnityImport, UnityExport, UnityProcessImport, UnityListView, UnityDetailUpdateAPIView

urlpatterns = patterns('',
	url(r'^projects/(?P<project_slug>[-\w]+)/unitytypes/create$', UnityTypeCreateView.as_view(), name='unity_types_create'),
#	url(r'^projects/(?P<project_slug>[-\w]+)/unities/$', UnityListView.as_view(), name='unities_list'),
#	url(r'^projects/(?P<project_slug>[-\w]+)/unities/(?P<slug>[-\w]+)/$', UnityDetailUpdateAPIView.as_view(), name='unity_detail'),
    url(r'^projects/(?P<project_slug>[-\w]+)/import/unities/$', UnityImport.as_view(), name='unities_import'),
    url(r'^projects/(?P<project_slug>[-\w]+)/export/unities/$', UnityExport.as_view(), name='unities_export'),
    url(r'^projects/(?P<project_slug>[-\w]+)/process_import/unities/$', UnityProcessImport.as_view(), name='unities_process_import'),
)

persons/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import random
import datetime
from hashlib import sha1
from django.core.exceptions import ValidationError
from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.template import defaultfilters
from django.template.loader import render_to_string
from sesamo.tasks import SendEmail
from units.models import Unity
from projects.models import Project

segment_choices= (
	("high","Altamente probable"),
	("medium","Medianamente probable"),
	("low","Poco probable"),
)

adquisition_channel_choices = (
	("room", "Sala de Ventas"),
	("fair", "Feria"),
	("phone", "Telefono"),
	("press", "Publicación en prensa"),
	("office", "Oficina"),
	("referal", "Referido"),
	("web", "Página Web"),
	("radio", "Radio"),
	("other", "Otros")
)

gender_choices = (
	("masculino", "Masculino"),
	("femenino", "Femenino")
)
#Cedula
#Direccion de notificacion
#Telefono de notificacion
#Fecha de Nacimiento
#Telefono fijo


CIVIL_STATUS_CHOICES = (
	('soltero', 'Soltero'),
	('casado', 'Casado'),
	('viudo', 'Viudo'),
	('union-libre', 'Union Libre'),
)


#TODO: Probably should make Pool a segment for easier filtering and SegmentLog tracking

class Person(models.Model):
	first_name = models.CharField(max_length=100, blank=False, null=False)
	last_name = models.CharField(max_length=100, blank=False, null=False)
	cellphone = models.CharField(max_length=20, blank=True, null=True)
	phone = models.CharField(max_length=15, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	unity_of_interest = models.ForeignKey(Unity, blank=True, null=True)
	adquisition_channel = models.CharField(max_length=100, choices=adquisition_channel_choices)
	segment = models.CharField(max_length=10, choices=segment_choices, default="low", blank=False, null=False)
	assigned_to = models.ForeignKey(settings.AUTH_PROFILE_MODULE, blank=True, null=True)
	sold = models.BooleanField(default=False)
	lost = models.BooleanField(default=False)
	is_client = models.BooleanField(default=False)
	gender = models.CharField(max_length=30, choices=gender_choices, blank=True, null=True)
	identity = models.CharField(max_length=30, blank=True, null=True)
	expedition_place = models.CharField(max_length=30, blank=True, null=True)
	notification_address = models.CharField(max_length=100, blank=True, null=True)
	notification_phone = models.CharField(max_length=20, blank=True, null=True)
	city_of_residence = models.CharField(max_length=50)
	birthday = models.DateField(blank=True, null=True)
	civil_status = models.CharField(max_length=20, blank=True, null=True, choices=CIVIL_STATUS_CHOICES)
	average_income = models.DecimalField(max_digits=10,decimal_places=2,blank=True,null=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	timestamp_for_sold = models.DateTimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
	project = models.ForeignKey(Project)
	last_update = models.DateTimeField(blank=True, null=True)
	slug = models.CharField(max_length=500)

	def get_person_full_name(self):
		full_name = "{} {}".format(self.first_name, self.last_name)
		return full_name

	def get_last_update(self):
		last_activity = self.activities.order_by("timestamp").last()
		last_note = self.notes.order_by("timestamp").last()
		if last_activity is not None and last_note is not None:
			if last_activity.timestamp > last_note.timestamp:
				return last_activity.timestamp
			else:
				return last_note.timestamp
		elif last_activity is None and last_note is None:
			return None
		elif last_activity is not None and last_note is None:
			return last_activity.timestamp
		elif last_activity is None and last_note is not None:
			return last_note.timestamp

	def set_last_update(self):
		self.last_update = self.get_last_update()
		self.save()

	def _create_segment_record(self):
		payload = {
			"person_id":self.pk,
			"segment":self.segment,
			"assigned_to":self.assigned_to
		}
		PersonSegmentLogRecords.objects.create(**payload)

	def save(self, *args, **kwargs):
		if not self.pk:
			self.slug = defaultfilters.slugify(self.get_person_full_name())
			while True:
				try:
					person_with_slug_exists = Person.objects.get(slug__iexact=self.slug)
					if person_with_slug_exists:
						self.slug = "{0}-{1}".format(self.slug, sha1(str(random.random()).encode('utf-8')).hexdigest()[:5])
				except Person.DoesNotExist: break
			super(Person, self).save(*args, **kwargs)
			self._create_segment_record()
		else:
			try:
				original_instance = Person.objects.get(pk=self.pk)
				if original_instance.sold == False and self.sold == True:
					self.timestamp_for_sold = datetime.datetime.today()

				if original_instance.segment != self.segment or original_instance.assigned_to != self.assigned_to:
					self._create_segment_record()
			except Exception as err:
				print (err)
			super(Person, self).save(*args, **kwargs)


	def __str__(self, *args, **kwargs):
		return self.get_person_full_name()

class PersonSegmentLogRecords(models.Model):
	"""Tracks the segments a Person has belonged to over time"""
	person = models.ForeignKey(Person, related_name='segment_log_records')
	assigned_to = models.ForeignKey(settings.AUTH_PROFILE_MODULE, blank=True, null=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	segment = models.CharField(max_length=10, choices=segment_choices, blank=False, null=False)

	def __str__(self):
		return "{} segment log. {}".format(
			self.person.get_person_full_name(),
			self.timestamp)


activity_types = (
	("llamada","Hacer llamada"),
	("email","Enviar correo"),
	("reunion","Reunion"),
	("visita", "Visita a Sala")
)

class OrderLog(models.Model):
	project = models.ForeignKey(Project)
	salesperson = models.ForeignKey(settings.AUTH_PROFILE_MODULE, blank=False, null=False, related_name="presale_orderlog")
	data = JSONField()

	def validate_unique(self, *args, **kwargs):
		qs = OrderLog.objects.filter(project=self.project, salesperson= self.salesperson)
		if qs.exists():
			raise ValidationError("OrderLog already exist. Try updating the existing log instead")

	def save(self, *args, **kwargs):
		if not self.pk:
			self.validate_unique()
		super(OrderLog, self).save(*args, **kwargs)

	def __str__(self, *args, **kwargs):
		return ("{} / {}".format(self.project, self.salesperson))


class Activity(models.Model):
	done = models.BooleanField(default=False)
	person = models.ForeignKey(Person, related_name="activities")
	project = models.ForeignKey(Project)
	activity_type = models.CharField(max_length=30, choices=activity_types)
	description = models.TextField(max_length=1000)
	scheduled_date = models.DateTimeField()
	assigned_to = models.ForeignKey(settings.AUTH_PROFILE_MODULE, blank=False, null=False, related_name="assigned_to")
	timestamp = models.DateTimeField(auto_now_add=True)
	checked_as_done_timestamp = models.DateTimeField(null=True, blank=True)

	def __str__(self, *args, **kwargs):
		return self.activity_type

	def save(self, *args, **kwargs):
		super(Activity, self).save(*args, **kwargs)
		self.person.last_update = datetime.datetime.now()
		self.person.save()

class Note(models.Model):
	person = models.ForeignKey(Person, related_name="notes")
	note = models.TextField(max_length=2000)
	assigned_to = models.ForeignKey(settings.AUTH_PROFILE_MODULE, related_name="assigned_notes", blank=False, null=False)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return ("Note on {}".format(self.person.get_person_full_name()))

	def save(self, *args, **kwargs):
		super(Note, self).save(*args, **kwargs)
		self.person.last_update = datetime.datetime.now()
		self.person.save()

persons/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from units.models import Unity
from .models import Person, Activity, Note

class PersonModelForm(forms.ModelForm):
	class Meta:
		model = Person
		fields = [
			"first_name", 
			"last_name", 
			"cellphone", 
			"phone", 
			"email", 
			"unity_of_interest", 
			"adquisition_channel", 
			"segment", 
		]

	def __init__(self, project, *args, **kwargs):
		super(PersonModelForm, self).__init__(*args, **kwargs)
		try:
			self.fields["unity_of_interest"].queryset = Unity.objects.filter(project=project)
		except:
			pass

class ActivityModelForm(forms.ModelForm):
	class Meta:
		model = Activity
		fields = [
			"activity_type",
			"description",
			"scheduled_date",
		]

class NoteModelForm(forms.ModelForm):
	class Meta:
		model = Note
		fields = [
			"note"
		]

#	def clean(self):
#		cleaned_data = super(AddProfileForm, self).clean()
#		unity_of_interest = cleaned_data.get("unity_of_interest")
#		send_automated_quotation = cleaned_data.get("send_automated_quotation")

#		if send_automated_quotation and not unity_of_interest:
#			raise forms.ValidationError(
#                    "Para enviar una cotización automática debes especificar una unidad de interes"
#                )
#		else:
#			return cleaned_data

templates/persons/activity_list.html
{% extends "base_app.html" %}
{% load static from staticfiles %}
<div class="segment">
{% block main-container %}
		<div ng-controller='mainController'>
		<div ng-view></div>
{% endblock %}
</div>
{% block custom-js %}
	<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-route.min.js"></script>
	<script data-require="ui-bootstrap@*" data-semver="0.12.1" src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.12.1.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-animate.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-aria.min.js"></script>
	<script src="https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.1/angular-material.js"></script>

	<script src="{% static "js/custom-angular.js" %}"></script>

{% endblock %}

templates/persons/office_initial.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/app/css/office.css">
    <title>Sesamo</title>
  </head>

  <body>
    <div id="app">
    </div>
    <script src='/static/app/js/office.js'></script>
  </body>
</html>

templates/persons/person_detail.html
{% extends "base_app.html" %}
{% block title %}Invita a tu equipo a unirse a este proyecto{% endblock %}
{% load persons_tags %}

{% block main-container %}
<div class="box-typical box-typical-full-height">
                <div class="add-customers-screen tbl">
                        <div class="add-customers-screen-user">
                            <i class="font-icon font-icon-user"></i>
                        </div>
            <h2 class="welcome-title">{{person.get_person_full_name}}</h2>
            <p class="lead color-blue-grey-lighter">Envía una invitación automática a las personas de tu equipo<br/> Sólo tienes que poner su email y su rol dentro de el equipo.</p>
            <h1>Activity Form</h1>
            {{activity_form.as_p}}
            <h1>Note Form</h1>
            {{note_form.as_p}}
        </div>
        <p>Documentos Adjuntos:</p>
        {% get_quotations person project as quotations %}
        {% if quotations %}
            {% for quotation in quotations %}
                <a href="{% url "download_quotation" quotation.pk %}" target="_blank">Cotización {{quotation.unity}}</a>
            {% endfor %}
        {% endif %}
    </div>
</div><!--.box-typical-->
{% endblock %}

templates/persons/person_form.html
{% extends "base_app.html" %}
{% load static from staticfiles %}

{% block title %}Create persona{% endblock %}

{% block main-container %}
	<!-- HARDCODED FORM FOR CREATEVIEW -->
<div class="page-content" ng-controller="searchController">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xl-10">
					<section class="box-typical steps-numeric-block personaForm">
						<div class="steps-numeric-header">
							<div class="steps-numeric-header-in">
								<ul>
									<li class="active"><div class="item"><span class="num">1</span>Registro de una persona</div></li>
									<li><div class="item"><span class="num">2</span>Generación de cotización</div></li>
								</ul>
							</div>
						</div>

						<div class="steps-numeric-inner">
							<header class="steps-numeric-title">Información de la persona</header>
							<form method="POST" id="personForm">
							{% csrf_token %}
								<div class="form-group">
									<div class="row form-element__fullname">
										<div class="col-md-6">
											<label>Nombre:</label>
											<input id="id_first_name" class="form-control form-element" maxlength="100" name="first_name" type="text" />
											<div class="form-element__required">Campo requerido</div>
										</div>
										<div class="col-md-6">
											<label>Apellido:</label>
											<input id="id_last_name" class="form-control form-element" maxlength="100" name="last_name" type="text" />
											<div class="form-element__required">Campo requerido</div>
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label>Celular:</label>
											<input id="id_cellphone" class="form-control" maxlength="20" name="cellphone" type="text" />
										</div>
										<div class="col-md-6">
											<label>Teléfono Fijo:</label>
											<input id="id_phone" class="form-control" maxlength="15" name="phone" type="text" />
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label>Correo Electrónico:</label>
											<input id="id_email" class="form-control" maxlength="254" name="email" type="email" />
										</div>
										<div class="col-md-6">
											<label>Origen:</label>
											<select id="id_adquisition_channel" name="adquisition_channel" class="form-element bootstrap-select bootstrap-select-arrow">
												{% for value, key in form.fields.adquisition_channel.choices %}
	        										<option value="{{value}}">{{key}}</option>
	    										{% endfor %}
											</select>
											<div class="form-element__required">Campo requerido</div>
											<br/>
											<br/>
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label>Segmento:</label>
											<select id="id_segment" name="segment" class="form-element bootstrap-select bootstrap-select-arrow">
												{% for value, key in form.fields.segment.choices %}
	        										<option value="{{value}}">{{key}}</option>
	    										{% endfor %}
											</select>
											<br/>
											<br/>
										</div>
										<div class="col-md-6">
											<label>Unidad de Interés:</label>
											<select  id="id_unity_of_interest" name="unity_of_interest" class="form-element bootstrap-select bootstrap-select-arrow" data-live-search="true">
												{% for value, key in form.fields.unity_of_interest.choices %}
	        										<option value="{{value}}">{{key}}</option>
	    										{% endfor %}
											</select>
											<div class="form-element__required">Campo requerido</div>
											<br /><br />
											<br/>
											<br/>
										</div>
									</div><!--.row-->
								</div>
								<button class="btn btn-inline btn-primary" onclick="onSubmit(event)">Guardar Persona</button>
							</form>
						</div>

					</section><!--.steps-numeric-block-->
				</div>
			</div><!--.row-->
		</div><!--.container-fluid-->
	</div><!--.page-content-->
{% endblock %}

{% block custom-js %}
	<script>

		var $inputs = $('input.form-element');
		var $selects = $('select.form-element');
		var invalidClassName = 'form-element--invalid';

		function onChangeHandler () {
			var $el = verifyElement($(this));

			var hasInvalid = $el.hasClass(invalidClassName);

			if (hasInvalid) {
				$el.removeClass(invalidClassName);
				$el.parent().find('div.form-element__required').hide();
			}
		}

		// Event handlers
		$inputs.keyup(onChangeHandler)
		$selects.change(onChangeHandler)

		// Submit
		function onSubmit (event) {
			event.preventDefault();

			$inputs.each(function (index) {
				var $el = $(this);

				if (!$el.val()) {
					$el.parent().find('div.form-element__required').show();
					$el.addClass(invalidClassName)
				}
			});

			$selects.each(function (index) {
				var $el = $(this);

				if (!$el.val()) {
					$el.parent().parent().find('div.form-element__required').show();
					$el.parent().addClass(invalidClassName);
				}
			});

			var isValid = $('.form-group .form-element--invalid').length === 0;

			if (isValid) {
				$('#personForm').submit();
			}
		}

		// Helpers
		function verifyElement ($el) {
			var isSelect = $el.is("select");

			if (isSelect) {
				return $el.parent();
			}

			return $el;
		}

	</script>

{% endblock %}

templates/persons/quotation_template.html
{% extends "easy_pdf/base.html" %}
{% load static from staticfiles %}
{% load humanize %}

{% block extra_style %}
    <style type="text/css">
        body {
            font-family: "Helvetica", "sans-serif";
            color: #333333;
            font-size: 16px;
        }
        .date{
            display: inline-block;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="content">
        <div class="main">
            <h2>Villa Para&iacute;so</h2>
            <h5 style="font-size: 18px;">Cotizaci&oacute;n de Apartamento {{apartment}}</h5>
            <p>Fecha de cotizaci&oacute;n: <span style="float: right;">{{today}}</span></p>

            <h4>Informaci&oacute;n del apartamento</h4>

            <p>Area Constru&iacute;da: <span style="float: right;">{{unity.unity_type.built_area}}m2</span></p>
            <p>Area Privada: <span style="float: right;">{{unity.unity_type.private_area}}m2</span></p>
            <p>Ba&ntilde;os: <span style="float: right;">{{unity.unity_type.bathrooms}}</span></p>
            <p>Habitaciones: <span style="float: right;">{{unity.unity_type.bedrooms}}</span></p>


            <h4>Valores</h4>

            <p>Precio del apartamento: <span style="float: right;"><b>{{apartment_price|intcomma}}</b></span></p>
            <p>Valor de la Cuota Inicial: <span style="float: right;">{{thirty_percent|intcomma}}</span></p>
            <p>Valor del Credito a Solicitar: <span style="float: right;">{{credit_to_request|intcomma}}</span></p>

            <h4>Forma de Pago de la Cuota Inicial</h4>
            <p>Separaci&oacute;n: <span style="float: right;"><b>{{booking_price|intcomma}}</b></span></p>
            <p>Tus ahorros: <span style="float: right;">{{savings|intcomma}}</span></p>
            <p>Tus cesant&iacute;as: <span style="float: right;">{{severance|intcomma}}</span></p>
            <p>Tu subsidio: <span style="float: right;">{{subsidy|intcomma}}</span></p>
            <p>Otros: <span style="float: right;">{{others|intcomma}}</span></p>
            <p>Saldo de la Cuota Inicial: <span style="float: right;">{{initial_fee_residue|intcomma}}</span></p>
            <p>Pagas el saldo en {{months_to_deliver}} cuotas mensuales de : <span style="float: right;">{{monthly_fees|intcomma}}</span></p>
        </div>
        <p style="margin-top: 50px; font-size: 12px">* Otros costos como gastos notariales y de registro, aval&uacute;os y tramites para solicitud de cr&eacute;dito, entre otros, son valores propocionales que se detallaran al momento de la separaci&oacute;n<br>* Esta cotizaci&oacute;n tiene una validez de 4 d&iacute;as<br> * Los apartamentos se separan unicamente despues de recibir el soporte de consignaci&oacute;n por parte del cliente</p>
    </div>
{% endblock %}