presales/urls.py
from django.conf.urls import patterns, url
from .views import QuotationCreateView, get_quotation, get_quickquotation

urlpatterns = patterns('',
	url(r'^projects/(?P<project_slug>[-\w]+)/person/(?P<person_slug>[-\w]+)/(?P<unity_slug>[-\w]+)/quotation/$', QuotationCreateView.as_view(), name='create_quotation'),
	url(r"^download/quotation/(?P<pk>[-\w]+)/$", get_quotation, name="download_quotation"),
	url(r"^download/quickquotation/(?P<pk>[-\w]+)/$", get_quickquotation, name="download_quickquotation")
)

units/urls.py
from django.conf.urls import patterns, url
from .views import UnityTypeCreateView, UnityImport, UnityExport, UnityProcessImport, UnityListView, UnityDetailUpdateAPIView

urlpatterns = patterns('',
	url(r'^projects/(?P<project_slug>[-\w]+)/unitytypes/create$', UnityTypeCreateView.as_view(), name='unity_types_create'),
#	url(r'^projects/(?P<project_slug>[-\w]+)/unities/$', UnityListView.as_view(), name='unities_list'),
#	url(r'^projects/(?P<project_slug>[-\w]+)/unities/(?P<slug>[-\w]+)/$', UnityDetailUpdateAPIView.as_view(), name='unity_detail'),
    url(r'^projects/(?P<project_slug>[-\w]+)/import/unities/$', UnityImport.as_view(), name='unities_import'),
    url(r'^projects/(?P<project_slug>[-\w]+)/export/unities/$', UnityExport.as_view(), name='unities_export'),
    url(r'^projects/(?P<project_slug>[-\w]+)/process_import/unities/$', UnityProcessImport.as_view(), name='unities_process_import'),
)

presales/models.py
from django.conf import settings
from django.db import models
from django.template.loader import render_to_string
from sesamo.tasks import SendEmail
from persons.models import Person
from units.models import Unity
from accounts.models import UserProfile

class Quotation(models.Model):
	person = models.ForeignKey(Person, related_name="quotations", on_delete=models.CASCADE)
	unity = models.ForeignKey(Unity)
	subsidy = models.IntegerField(default=0, blank=True)
	savings = models.IntegerField(default=0, blank=True)
	severance = models.IntegerField(default=0, blank=True)
	others = models.IntegerField(default=0, blank=True)
	monthly_income = models.IntegerField(default=0, blank=True)
	months_to_deliver = models.IntegerField(default=0, blank=True)
	sent = models.BooleanField(default=False)

	def send_quotation(self, *args, **kwargs):
		to_email = self.person.email
		to_name = self.person.get_person_full_name()
		from_email = settings.DEFAULT_EMAIL_SENDER
		from_name = settings.DEFAULT_NAME_SENDER
		subject = "Aqui tienes tu cotizacion"
		template_name = settings.QUOTATION_TEMPLATE_ID
		html_text = render_to_string("presales/emails/quotation_email_template.html")
		substitutions = {
			"-name-" : [self.person.first_name], 
			"-pk-" : [str(self.pk)]
		}
		SendEmail.delay(
			to_email, 
			to_name, 
			from_email, 
			from_name, 
			subject, 
			template_name, 
			html_text, 
			substitutions, 
		)
		#HACER AQUI TRACKING DE ERRORES ANTES DE RETORNAR TRUE
		return True

	def save(self, *args, **kwargs):
		super(Quotation, self).save(*args, **kwargs)
		if not self.sent:
			print ("Not sent")
			try:
				quotation_sent = self.send_quotation()
				if quotation_sent:
					self.sent = True
					super(Quotation, self).save(*args, **kwargs)
			except:
				pass

	def __str__(self):
		return self.unity.name

class QuickQuotation(models.Model):
	email = models.EmailField()
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	price = models.IntegerField()
	months_to_deliver = models.IntegerField()
	savings = models.IntegerField(default=0, blank=True)
	sent = models.BooleanField(default=False)
	unity = models.ForeignKey(Unity)

	def get_months_to_deliver(self, *args, **kwargs):
		return self.months_to_deliver

	def send_quotation(self, *args, **kwargs):
		to_email = self.email
		to_name = self.first_name
		from_email = settings.DEFAULT_EMAIL_SENDER
		from_name = settings.DEFAULT_NAME_SENDER
		subject = "Aqui tienes tu cotizacion"
		template_name = settings.QUOTATION_TEMPLATE_ID
		html_text = render_to_string("presales/emails/quickquotation_email_template.html")
		substitutions = {
			"-name-" : [to_name], 
			"-pk-" : [str(self.pk)]
		}
		#HACER MANEJO DE EXCEPCIONES, REAL, AQUI
		try:
			SendEmail.delay(
				to_email, 
				to_name,
				from_email, 
				from_name, 
				subject, 
				template_name, 
				html_text, 
				substitutions, 
			)
			return True
		except Exception as err:
			print  ("THERE WAS AN EXCEPTION WHILE CALLING THE TASK: ")
			print (err)

	def save(self, *args, **kwargs):
		if not self.pk:
			super(QuickQuotation, self).save(*args, **kwargs)
			try:
				Person.objects.create(first_name=self.first_name, last_name=self.last_name, email=self.email, project=self.unity.project)
			except Exception as err:
				print ("ERROR: {}".format(err))
		if not self.sent:
			try:
				quickquotation_sent = self.send_quotation()
				if quickquotation_sent:
					self.sent = True
					super(QuickQuotation, self).save(*args, **kwargs)
			except:
				pass

class VirtualBooking(models.Model):
	closed = models.BooleanField(default=False)
	assigned_to = models.ForeignKey(settings.AUTH_PROFILE_MODULE, blank=True, null=True)
	person = models.ForeignKey(Person)
	unity = models.ForeignKey(Unity)
	notification_cellphone = models.CharField(max_length=100)
	notification_email = models.EmailField()
	timestamp = models.DateField(auto_now_add=True)


class Sale(models.Model):
	unity = models.ForeignKey(Unity)
	salesperson = models.OneToOneField(UserProfile)
	sale_date = models.DateField()
	timestamp = models.DateField(auto_now=True)
	buyer = models.ForeignKey(Person)
	

presales/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Quotation

class IntegerCurrencyInput(forms.TextInput):
    def render(self, name, value, attrs=None):
        from django.contrib.humanize.templatetags.humanize import intcomma
        if value:
            value = "$%s" % intcomma(value)
        return super(IntegerCurrencyInput, self).render(name, value, attrs)

class IntegerCurrencyField(forms.IntegerField):
    widget = IntegerCurrencyInput
    
    def clean(self, value):
        if value:
            if value[0] == "$": value = value[1:] # Cut off the dollar sign
            value = value.replace('.', '') # Remove Commas
        print (value)
        value = super(IntegerCurrencyField, self).clean(value)
        return int(value) if value else value


class QuotationModelForm(forms.ModelForm):
	subsidy = IntegerCurrencyField()
	savings = IntegerCurrencyField()
	severance = IntegerCurrencyField()
	monthly_income = IntegerCurrencyField()
	others = IntegerCurrencyField()

	class Meta:
		model = Quotation
		fields = [
			"subsidy",
			"savings",
			"severance",
			"months_to_deliver",
			"monthly_income", 
			"others"
		]

presales/views.py
from datetime import datetime
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from rest_framework import generics, filters
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.views import APIView
from .models import Quotation, QuickQuotation, VirtualBooking
from .forms import QuotationModelForm
from .serializers import QuotationSerializer, QuickQuotationSerializer, VirtualBookingSerializer, VirtualBookingSerializerWithPersonSerializer
from .filters import PersonFilter
from django.template import RequestContext
from django.template.loader import get_template

from sesamo.mixins import SlugManagerMixin

from weasyprint import HTML, CSS

from persons.models import Person
from persons.serializers import PersonSmallSerializer

@method_decorator(login_required, name='dispatch')
class VirtualBookingCreateView(generics.CreateAPIView):
    queryset = VirtualBooking.objects.all()
    serializer_class = VirtualBookingSerializer

@method_decorator(login_required, name='dispatch')
class VirtualBookingForUnityListAPIView(SlugManagerMixin, generics.ListAPIView):
	model_class = VirtualBooking
	serializer_class = VirtualBookingSerializerWithPersonSerializer

	def get_queryset(self):
		project = self.get_project()
		unity = self.kwargs.get("id")
		virtual_bookings = VirtualBooking.objects.filter(unity=unity, closed=False)
		return virtual_bookings

@method_decorator(login_required, name='dispatch')
class PersonSearchView(SlugManagerMixin, generics.ListAPIView):
    model_class = Person
    queryset = Person.objects.all()
    serializer_class = PersonSmallSerializer
    filter_backends = (filters.SearchFilter, DjangoFilterBackend)
    filter_class = PersonFilter
    search_fields = ("^first_name", "^last_name")

    def get_queryset(self):
        project = self.get_project()
        persons_in_project = Person.objects.filter(project=project)
        return persons_in_project

@method_decorator(login_required, name='dispatch')
class QuotationCreateView(SlugManagerMixin, CreateView):
	model = Quotation
	form_class = QuotationModelForm

	def form_valid(self, form):
		person = self.get_person()
		project = self.get_project()
		unity = self.get_unity()
		self.object = form.save(commit=False)
		self.object.person = person
		self.object.unity = unity
		self.object.save()
		super(QuotationCreateView, self).form_valid(form)
		return HttpResponseRedirect(reverse("person_tracking", kwargs={"project_slug": project.slug, "person_slug": person.slug}))

	def get_success_url(self):
		project = self.get_project()
		person = self.get_person()
		return reverse("person_tracking", kwargs={"project_slug": project.slug, "person_slug": person.slug})

def get_quotation(request, pk):
	html_template = get_template("presales/quotation_template.html")
	quotation = get_object_or_404(Quotation, pk=pk)
	booking_price_for_this_quotation = quotation.unity.project.booking_price
	thirty_percent = int(0.3 * int(quotation.unity.price))
	credit_to_request = int(int(quotation.unity.price) - thirty_percent)
	initial_fee_residue = thirty_percent - (int(quotation.savings) + int(booking_price_for_this_quotation) + int(quotation.severance) + int(quotation.subsidy) + int(quotation.others))
	monthly_fees = int(int(initial_fee_residue) / int(quotation.months_to_deliver))
	today = str(datetime.today().date())
	data_dict = {
		'pagesize':"A4",
		'title': 'Cotizacion de Apartamento {0}'.format(quotation.unity.name),
		'apartment': quotation.unity.name,
		'apartment_price': int(quotation.unity.price),
		'thirty_percent': thirty_percent,
		'booking_price': booking_price_for_this_quotation,
		'savings': int(quotation.savings),
		'severance': int(quotation.severance),
		'subsidy': int(quotation.subsidy),
		'initial_fee_residue': initial_fee_residue,
		'monthly_fees': monthly_fees,
		'months_to_deliver': quotation.months_to_deliver,
		'credit_to_request': credit_to_request,
		'today': today,
		'unity': quotation.unity,
		'others': quotation.others
	}

	rendered_html = html_template.render(RequestContext(request, data_dict)).encode(encoding="UTF-8")

	pdf_file = HTML(string=rendered_html).write_pdf(stylesheets=[CSS(settings.STATIC_ROOT + "/css/quotation.css")])

	http_response = HttpResponse(pdf_file, content_type='application/pdf')
	http_response['Content-Disposition'] = 'filename="cotizacion.pdf"'
	return http_response

@method_decorator(login_required, name='dispatch')
class QuotationCreateAPIView(generics.CreateAPIView):
	queryset = Quotation.objects.all()
	serializer_class = QuotationSerializer

	def get_serializer_context(self):
		return {
			'request': self.request,
			'format': self.format_kwarg,
			'view': self
		}

@method_decorator(login_required, name='dispatch')
class QuickQuotationCreateAPIView(generics.CreateAPIView):
	queryset = QuickQuotation.objects.all()
	serializer_class = QuickQuotationSerializer

	def get_serializer_context(self):
		return {
			'request': self.request,
			'format': self.format_kwarg,
			'view': self
		}

#QUICK-QUOTATIONS

def get_quickquotation(request, pk):
	html_template = get_template("presales/quickquotation_template.html")
	quickquotation = get_object_or_404(QuickQuotation, pk=pk)
	booking_price_for_this_quotation = quickquotation.unity.project.booking_price
	thirty_percent = int(0.3 * int(quickquotation.unity.price))
	credit_to_request = int(int(quickquotation.unity.price) - thirty_percent)
	initial_fee_residue = thirty_percent - (int(quickquotation.savings) + int(booking_price_for_this_quotation))
	monthly_fees = int(int(initial_fee_residue) / int(quickquotation.months_to_deliver))
	today = str(datetime.today().date())
	data_dict = {
		'pagesize':"A4",
		'title': 'Cotizacion de Apartamento {0}'.format(quickquotation.unity.name),
		'apartment': quickquotation.unity.name,
		'apartment_price': int(quickquotation.unity.price),
		'thirty_percent': thirty_percent,
		'booking_price': booking_price_for_this_quotation,
		'savings': int(quickquotation.savings),
		'initial_fee_residue': initial_fee_residue,
		'monthly_fees': monthly_fees,
		'months_to_deliver': quickquotation.months_to_deliver,
		'credit_to_request': credit_to_request,
		'today': today,
		'unity': quickquotation.unity,
	}

	rendered_html = html_template.render(RequestContext(request, data_dict)).encode(encoding="UTF-8")

	pdf_file = HTML(string=rendered_html).write_pdf(stylesheets=[CSS(settings.STATIC_ROOT + "/css/quotation.css")])

	http_response = HttpResponse(pdf_file, content_type='application/pdf')
	http_response['Content-Disposition'] = 'filename="cotizacion.pdf"'
	return http_response


class SendNotificationView(SlugManagerMixin, APIView):
	def post(self, request, *args, **kwargs):
		project = self.get_project()
		report_serializer = ReportSerializer(data=request.data)
		if report_serializer.is_valid():
			unities_ids = notification_serializer.data["unities"]
			html_snippet = notification_serializer.data["html_snippet"]
			tower_number = notification_serializer.data["tower_number"]
			request_user_id = request.user.id
			project_id = project.id
			task = SendNotificationsTask.delay(request_user_id, project_id, unities_ids, html_snippet, tower_number)
			data = {"task_id":task.id}
			return Response(data=data, status=status.HTTP_200_OK)
		else:
			return Response(status= status.HTTP_400_BAD_REQUEST)

templates/presales/quickquotation_template.html
{% extends "easy_pdf/base.html" %}
{% load static from staticfiles %}
{% load humanize %}

{% block extra_style %}
    <style type="text/css">
        body {
            font-family: "Helvetica", "sans-serif";
            color: #333333;
            font-size: 16px;
        }
        .date{
            display: inline-block;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="content">
        <div class="main">
            <h2>Villa Para&iacute;so</h2>
            <h5 style="font-size: 18px;">Cotizaci&oacute;n de Apartamento {{apartment}}</h5>
            <p>Fecha de cotizaci&oacute;n: <span style="float: right;">{{today}}</span></p>

            <h4>Informaci&oacute;n del apartamento</h4>

            <p>Area Constru&iacute;da: <span style="float: right;">{{unity.unity_type.built_area}}m2</span></p>
            <p>Area Privada: <span style="float: right;">{{unity.unity_type.private_area}}m2</span></p>
            <p>Ba&ntilde;os: <span style="float: right;">{{unity.unity_type.bathrooms}}</span></p>
            <p>Habitaciones: <span style="float: right;">{{unity.unity_type.bedrooms}}</span></p>


            <h4>Valores</h4>

            <p>Precio del apartamento: <span style="float: right;"><b>{{apartment_price|intcomma}}</b></span></p>
            <p>Valor de la Cuota Inicial: <span style="float: right;">{{thirty_percent|intcomma}}</span></p>
            <p>Valor del Credito a Solicitar: <span style="float: right;">{{credit_to_request|intcomma}}</span></p>

            <h4>Forma de Pago de la Cuota Inicial</h4>
            <p>Separaci&oacute;n: <span style="float: right;"><b>{{booking_price|intcomma}}</b></span></p>
            <p>Ahorros: <span style="float: right;"><b>{{savings|intcomma}}</b></span></p>
            <p>Pagas el saldo en {{months_to_deliver}} cuotas mensuales de : <span style="float: right;">{{monthly_fees|intcomma}}</span></p>
        </div>
        <p style="margin-top: 50px; font-size: 14px">*Esta es una cotizaci&oacute;n r&aacute;pida, los costos podr&iacute;an variar en la medida en que se personalice con las cesant&iacute;as, subsidios y ahorros que el cliente disponga*
        <p style="margin-top: 50px; font-size: 12px">* Otros costos como gastos notariales y de registro, aval&uacute;os y tramites para solicitud de cr&eacute;dito, entre otros, son valores propocionales que se detallaran al momento de la separaci&oacute;n<br>* Esta cotizaci&oacute;n tiene una validez de 4 d&iacute;as<br> * Los apartamentos se separan unicamente despues de recibir el soporte de consignaci&oacute;n por parte del cliente</p>
    </div>
{% endblock %}

templates/presales/quotation_form.html
{% extends "base_app.html" %}
{% load static from staticfiles %}

{% block title %}Create persona{% endblock %}

{% block main-container %}
	<!-- HARDCODED FORM FOR CREATEVIEW -->
<div class="page-content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xl-10">
					<section class="box-typical steps-numeric-block quoteForm">
						<div class="steps-numeric-header">
							<div class="steps-numeric-header-in">
								<ul>
									<li><div class="item"><span class="num">1</span>Registro de una persona</div></li>
									<li class="active"><div class="item"><span class="num">2</span>Generación de cotización</div></li>
								</ul>
							</div>
						</div>

						<div class="steps-numeric-inner">
							<header class="steps-numeric-title">Información financiera</header>
							<form method="POST">
							{{form.errors}}
							{% csrf_token %}
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label for="id_monthly_income">Ingresos Mensuales</label>
											<input id="id_monthly_income" name="monthly_income" class="form-control moneyF" maxlength="20" type="text" value="0" />
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label for="id_savings">Ahorros programados</label>
											<input id="id_savings" class="form-control moneyF" maxlength="100" name="savings" type="text" value="0" />
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label for="id_severance">Cesantías</label>
											<input id="id_severance" class="form-control moneyF" maxlength="20" name="severance" type="text" value="0" />
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label for="id_others">Otros</label>
											<input id="id_others" name="others" class="form-control moneyF" maxlength="20" type="text" value="0" />
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label for="id_subsidy">Subsidio</label>
											<input id="id_subsidy" class="form-control moneyF" maxlength="100" name="subsidy" type="text" value="0"/>
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="row">
										<div class="col-md-6">
											<label for="id_months_to_deliver">Meses faltantes para entrega</label>
											<input id="id_months_to_deliver" class="form-control" maxlength="254" name="months_to_deliver" type="number" max="24" value="24" placeholder="Meses antes de entrega" validate/>
										</div>
									</div>
								</div>
								<button type="submit" class="btn btn-inline btn-primary">Generar Cotización</button>
							</form>
						</div>

					</section><!--.steps-numeric-block-->
				</div>
			</div><!--.row-->
		</div><!--.container-fluid-->
	</div><!--.page-content-->
{% endblock %}

{% block custom-js %}
	<script src="{% static "js/bootstrap-select.min.js" %}"></script>
	<script src="{% static "js/select2.full.min.js" %}"></script>
	<script src="{% static "js/autoNumeric-min.js" %}"></script>

	<script>
		$(document).ready(function(){
			//$('#tags-editor-textarea').tagEditor();

		    $('.moneyF').autoNumeric("init",{
		        aSep: '.',
		        aDec: ',',
		        vMin: '0',
		        aPad: 'false'
		    });
		});
	</script>
{% endblock %}

templates/presales/quotation_template.html
{% extends "easy_pdf/base.html" %}
{% load static from staticfiles %}
{% load humanize %}

{% block extra_style %}
    <style type="text/css">
        body {
            font-family: "Helvetica", "sans-serif";
            color: #333333;
            font-size: 16px;
        }
        .date{
            display: inline-block;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="content">
        <div class="main">
            <h2>Villa Para&iacute;so</h2>
            <h5 style="font-size: 18px;">Cotizaci&oacute;n de Apartamento {{apartment}}</h5>
            <p>Fecha de cotizaci&oacute;n: <span style="float: right;">{{today}}</span></p>

            <h4>Informaci&oacute;n del apartamento</h4>

            <p>Area Constru&iacute;da: <span style="float: right;">{{unity.unity_type.built_area}}m2</span></p>
            <p>Area Privada: <span style="float: right;">{{unity.unity_type.private_area}}m2</span></p>
            <p>Ba&ntilde;os: <span style="float: right;">{{unity.unity_type.bathrooms}}</span></p>
            <p>Habitaciones: <span style="float: right;">{{unity.unity_type.bedrooms}}</span></p>


            <h4>Valores</h4>

            <p>Precio del apartamento: <span style="float: right;"><b>{{apartment_price|intcomma}}</b></span></p>
            <p>Valor de la Cuota Inicial: <span style="float: right;">{{thirty_percent|intcomma}}</span></p>
            <p>Valor del Credito a Solicitar: <span style="float: right;">{{credit_to_request|intcomma}}</span></p>

            <h4>Forma de Pago de la Cuota Inicial</h4>
            <p>Separaci&oacute;n: <span style="float: right;"><b>{{booking_price|intcomma}}</b></span></p>
            <p>Tus ahorros: <span style="float: right;">{{savings|intcomma}}</span></p>
            <p>Tus cesant&iacute;as: <span style="float: right;">{{severance|intcomma}}</span></p>
            <p>Tu subsidio: <span style="float: right;">{{subsidy|intcomma}}</span></p>
            <p>Otros: <span style="float: right;">{{others|intcomma}}</span></p>
            <p>Saldo de la Cuota Inicial: <span style="float: right;">{{initial_fee_residue|intcomma}}</span></p>
            <p>Pagas el saldo en {{months_to_deliver}} cuotas mensuales de : <span style="float: right;">{{monthly_fees|intcomma}}</span></p>
        </div>
        <p style="margin-top: 50px; font-size: 12px">* Otros costos como gastos notariales y de registro, aval&uacute;os y tramites para solicitud de cr&eacute;dito, entre otros, son valores propocionales que se detallaran al momento de la separaci&oacute;n<br>* Esta cotizaci&oacute;n tiene una validez de 4 d&iacute;as<br> * Los apartamentos se separan unicamente despues de recibir el soporte de consignaci&oacute;n por parte del cliente</p>
    </div>
{% endblock %}