units/urls.py
from django.conf.urls import patterns, url
from .views import UnityTypeCreateView, UnityImport, UnityExport, UnityProcessImport, UnityListView, UnityDetailUpdateAPIView

urlpatterns = patterns('',
	url(r'^projects/(?P<project_slug>[-\w]+)/unitytypes/create$', UnityTypeCreateView.as_view(), name='unity_types_create'),
#	url(r'^projects/(?P<project_slug>[-\w]+)/unities/$', UnityListView.as_view(), name='unities_list'),
#	url(r'^projects/(?P<project_slug>[-\w]+)/unities/(?P<slug>[-\w]+)/$', UnityDetailUpdateAPIView.as_view(), name='unity_detail'),
    url(r'^projects/(?P<project_slug>[-\w]+)/import/unities/$', UnityImport.as_view(), name='unities_import'),
    url(r'^projects/(?P<project_slug>[-\w]+)/export/unities/$', UnityExport.as_view(), name='unities_export'),
    url(r'^projects/(?P<project_slug>[-\w]+)/process_import/unities/$', UnityProcessImport.as_view(), name='unities_process_import'),
)

units/models.py
from __future__ import unicode_literals
import datetime
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.template import defaultfilters
#from alerts.models import Alert
from projects.models import Project
from .choices import status_choices

type_name_choices = (
	("apartamento", "Apartamento"),
	("casa", "Casa"),
	("local", "Local"),
	("parqueadero", "Parqueadero"),
)

unitytype_choices = (
	("tipo1","Tipo 1"),
	("tipo2","Tipo 2"),
	("tipo3","Tipo 3"),
	("tipo4","Tipo 4"),
	("tipo5","Tipo 5"),
	("tipo6","Tipo 6"),
)


class UnityType(models.Model):
	built_area = models.FloatField()
	bathrooms = models.IntegerField()
	bedrooms = models.IntegerField()
	project = models.ForeignKey(Project)
	unitytype_name = models.CharField(max_length=30, choices=unitytype_choices)
	type_name = models.CharField(max_length=30, choices=type_name_choices, blank=False)
	private_area = models.FloatField()

	def save(self, *args, **kwargs):
		self.type_name = self.type_name.lower()
		super(UnityType, self).save(*args, **kwargs)

	def __str__(self, *args, **kwargs):
		return self.get_type_name_display() + self.get_unitytype_name_display()


class Unity(models.Model):
	name = models.CharField(max_length=30, blank=False, null=False)
	nomenclature = models.CharField(max_length=100)
	real_estate_registration = models.CharField(max_length=30)
	project = models.ForeignKey(Project)
	unity_type = models.ForeignKey(UnityType)
	coefficient = models.FloatField()
	price = models.IntegerField()
	delivery_date = models.DateField()
	status = models.CharField(max_length=50, choices=status_choices, default="available")
	timestamp_for_status = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
	slug = models.SlugField()

	def create_alert(self, alert_type, unity, person, created_for):
		from alerts.models import Alert
		Alert.objects.create(
			alert_type=alert_type,
			unity=unity,
			person=person,
			created_for=created_for,
		)


	def save(self, *args, **kwargs):
		self.slug = defaultfilters.slugify(self.name)
		if self.pk is not None:
			try:
				original_instance = Unity.objects.get(pk=self.pk)
				if original_instance.status != self.status:
					self.timestamp_for_status = datetime.date.today()
			except Exception as err:
				print ("Error: {}".format(err))
			super(Unity, self).save(*args, **kwargs)
		else:
			super(Unity, self).save(*args, **kwargs)
			#ESTA LÓGICA DEBE DESARROLLARSE CUANDO TENGAMOS LOS ACUERDOS DE PAGO FUNCIONANDO
			# :3
			#if original_instance.status == "legalized" and self.status == "available":
			#	self.create_alert(
			#		alert_type="legalization_closed",
			#		unity=original_instance,
			#		person=original_instance.person_set.all()[0],
			#		created_for=original_instance.person_set.all()[0].assigned_to,
			#	)
	#	else:
	#		super(Unity, self).save(*args, **kwargs)
	#		from crm.models import UnityProfile
	#		obj = UnityProfile.objects.create(unity=self)

	def __str__(self, *args, **kwargs):
		return self.name

#class VirtualBooking(models.Model):
#	person = models.ForeignKey(Person)
#	sales_person = models.ForeignKey(settings.AUTH_PROFILE_MODULE, blank=True, null=True)
#	unity = models.ForeignKey(Unity)
#	timestamp = models.DateField(auto_now_add=True)

#	def save(self):
#		self.unity.status = "virtually_booked"
#		self.unity.save()
#		super(VirtualBooking, self).save()

units/forms.py
from django import forms
from .models import UnityType

LABEL_CHOICE = [
		("label", "Selecciona el tipo de unidad")
	]

class UnityTypeForm(forms.ModelForm):
	class Meta:
		model = UnityType
		fields = ["unitytype_name", "type_name", "private_area", "built_area", "bathrooms", "bedrooms"]

	def __init__(self, *args, **kwargs):
		super(UnityTypeForm, self).__init__(*args, **kwargs)
		self.fields["unitytype_name"].label = "Nombre del tipo. Ej: Tipo 1"
		self.fields["type_name"].label = "Tipo de unidad"
		self.fields["private_area"].label = "Area privada"
		self.fields["built_area"].label = "Area Construida"
		self.fields["type_name"].widget.attrs.update({'class' : 'browser-default'})
		self.fields['type_name'].choices = self.fields["type_name"].choices[1:]
		self.fields["unitytype_name"].widget.attrs.update({'class' : 'browser-default'})
		self.fields['unitytype_name'].choices = self.fields["unitytype_name"].choices[1:]

units/views.py
import csv
import os
import tempfile
from datetime import datetime
import django_filters
from django.conf import settings
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text
from django.views.generic import View, TemplateView, CreateView, ListView
from projects.models import Project
from import_export.forms import ImportForm
from import_export.forms import ConfirmImportForm
from import_export.formats import base_formats
from import_export.resources import modelresource_factory
from import_export import resources
from rest_framework import generics, filters, permissions, exceptions, viewsets
from rest_framework.response import Response
from sesamo.mixins import SlugManagerMixin
#from formalizations.models import UnityAlert
from .choices import status_choices
from .forms import UnityTypeForm
from .models import Unity, UnityType
from .serializers import UnitySerializer#, UnityUpdateSerializer
from .permissions import CanUpdateUnity
from .filters import UnityFilter
#START OF API VIEWS

@method_decorator(login_required, name='dispatch')
class UnityListAPIView(SlugManagerMixin, generics.ListAPIView):
    model_class = Unity
    serializer_class = UnitySerializer
    permission_classes = (permissions.IsAuthenticated,)

    def get_queryset(self):
        project = self.get_project()
        return self.model_class.objects.filter(project=project)

@method_decorator(login_required, name='dispatch')
class AvailableUnitiesListAPIView(SlugManagerMixin, generics.ListAPIView):
    model_class = Unity
    serializer_class = UnitySerializer
    permission_classes = (permissions.IsAuthenticated,)
    email_template = 'units/available_units_email.html'

    def send_email(self):
        user = self.request.user
        if user.email is not None:
            to_list = [user.email]
            from_email = settings.DEFAULT_EMAIL_SENDER
            from_name = settings.DEFAULT_NAME_SENDER
            subject = "Listado de unidades disponibles en el proyecto {}".format(self.project)
            data = {'available_units': self.q}
            body = render_to_string(self.email_template, data)
            email = EmailMessage(subject, body, from_email, to_list)
            email.send(fail_silently=False)

    def get_queryset(self):
        self.project = self.get_project()
        self.q = self.model_class.objects.filter(project=self.project).exclude(Q(status="sold") | Q(status="legalized"))
        if hasattr(self.kwargs, 'email') and self.kwargs.get('email') == True:
            try:
                self.send_email()
                return True
            except:
                print ("Failed")
        return self.q

@method_decorator(login_required, name='dispatch')
class UnityDetailUpdateAPIView(generics.RetrieveUpdateAPIView):
    model_class = Unity
    lookup_field = "id"
    queryset = Unity.objects.all()
    serializer_class = UnitySerializer
    permission_classes = (permissions.IsAuthenticated, CanUpdateUnity)


#class UnityDetailUpdateAPIView(SlugManagerMixin, viewsets.ModelViewSet):
#    model_class = Unity
#    queryset = Unity.objects.all()
#    serializer_class = UnitySerializer
#    create_update_serializer = UnityUpdateSerializer
#    permission_classes = (permissions.IsAuthenticated,)
#    lookup_field = "id"
#    lookup_url_kwarg = "id"

#    def get_serializer_class(self):
#        print ("GOT INTO SERIALIZER CLASS")
#        if self.action == 'retrieve':
#            print ("GOT INTO ACTION RETIREVE")
#            return self.detail_serializer
#        elif self.action == 'update':
#            print ("GOT INTO ACTION UPDATE")
#            return self.create_update_serializer

#    def update(self, request, *args, **kwargs):
#        request_usertype = request.user.user_profile.user_type
#        if request_usertype == "administrador_preventas" or request_usertype == "gerente":
#            serializer = self.serializer_class(data=request.data)
#            if serializer.is_valid():
#                serializer.save()
#                return Response(serializer.data)
#        else:
#            raise exceptions.PermissionDenied()

#class UnityAlertListAPIView(SlugManagerMixin, generics.ListAPIView):
#    model_class = UnityAlert
#    serializer_class = UnitySerializer
#    permission_classes = (permissions.DjangoModelPermissions,)

#    def get_queryset(self):
#        print (self.request.user)
#        user_profile = self.request.user.user_profile
#        return self.model_class.objects.filter(created_for=user_profile)
#END OF API VIEWS


#FUNCTIONS TO IMPORT-EXPORT UNITIES
class UnityResource(resources.ModelResource):

    def after_export(self, queryset, data, *args, **kwargs):
        """
        Override to add additional logic. Does nothing by default.
        """
        dataset = data
        i = 0
        last = dataset.height -1

        while i <= last:
            unitytype_id = dataset["unity_type"][0]
            try:
                unity_type = UnityType.objects.get(id=unitytype_id)
            except Exception as err:
                raise Exception("No se encuentra el tipo de unidad")

            unitytype_full_name = "{0}-{1}".format(unity_type.type_name, unity_type.unitytype_name)
            try:
                dataset.rpush(
                    (
                        dataset.get_col(0)[0],
                        dataset.get_col(1)[0],
                        dataset.get_col(2)[0],
                        dataset.get_col(3)[0],
                        unitytype_full_name,
                        dataset.get_col(5)[0],
                        dataset.get_col(6)[0],
                        dataset.get_col(7)[0],
                        dataset.get_col(8)[0],
                        dataset.get_col(9)[0],
                    )

                )
            except:
                raise Exception("La tabla no se pudo exportar")
            dataset.lpop()
            i = i + 1
        del dataset["project"]

    def before_import(self, dataset, dry_run, *args, **kwargs):
        project = kwargs['project']
        i = 0
        last = dataset.height - 1

        while i <= last:
            # Check if the unity type exists in DB
            unitytype = dataset["unity_type"][0].split("-")
            type_name = unitytype[0].lower()
            unitytype_name = unitytype[1].lower()
            try:
                unity_type = UnityType.objects.get(unitytype_name=unitytype_name, type_name=type_name, project=project)
            except UnityType.DoesNotExist:
                raise Exception("No se encuentra ese tipo de unidad")
            except UnityType.MultipleObjectsReturned:
                pass
            existing_unity_type = unity_type.id


            columns_indexes = ["dataset.get_col({0})".format(x) for x in range(0, len(dataset.headers))]

            #try:
                #lols = [(lambda x: dataset.get_col(x))(x) for x in range(len(dataset.headers))]
            #    print (lols)
            #except Exception as err:
            #    print (err)
            #    exit()

            #unitytype_index = dataset.headers.index("unity_type")
            #del(columns_indexes[unitytype_index])
            #columns_indexes.insert(unitytype_index, existing_unity_type)
            #print (columns_indexes)
            try:
                dataset.rpush(
                    tuple([existing_unity_type if dataset.headers.index("unity_type") == x else dataset.get_col(x)[0] for x in range(0, len(dataset.headers))])
                )
            except Exception as err:
                print (err)
                print ("MIERDERO")
            dataset.lpop()
            i = i + 1


        try:
            dataset["id"]
        except:
            try:
                dataset.append_col([None for row in range(len(dataset))], header='id')
            except:
                print ("Error agregando columna de ID al dataset")

        try:
            dataset.append_col([project.id for row in range(len(dataset))], header='project')
        except Exception as err:
            print (err)

    class Meta:
        model = Unity
        fields = (
            'id',
            'name',
            'nomenclature',
            'real_estate_registration',
            'unity_type',
            'coefficient',
            'price',
            'delivery_date',
            'project',
            'status'
        )
        export_order = (
            'id',
            'name',
            'nomenclature',
            'real_estate_registration',
            'unity_type',
            'coefficient',
            'price',
            'delivery_date',
        )

class UnityExport(View):
    model = Unity
    from_encoding = "utf-8"
    resource_class = UnityResource

    def get_resource_class(self):
        if not self.resource_class:
            return modelresource_factory(self.model)
        else:
            return self.resource_class

    def get_export_resource_class(self):
        """
        Returns ResourceClass to use for export.
        """
        return self.get_resource_class()

        resource = self.get_export_resource_class()()

    def get(self, *args, **kwargs ):
        project_slug = self.kwargs["project_slug"]
        project = get_object_or_404(Project, slug__iexact=project_slug)
        resource = self.get_export_resource_class()()
        result = resource.export(queryset=Unity.objects.filter(project=project).order_by("id"))
        response = HttpResponse(result.csv, content_type="csv")
        response['Content-Disposition'] = 'attachment; filename={0}-unidades.csv'.format(project.name)

templates/units/available_units_email.html
<html>


<body>
    
    {% for unit in available_units %}
       <p>Unidad {{unit}} - Estado: {{unit.status}}</p>
    {% endfor %}
</body>
</html>

templates/units/done.html
<!DOCTYPE html>
<html>
<head>
	<title>Done</title>
</head>
<body>
<h1>Done</h1>
</body>
</html>

templates/units/unity_list.html
{% extends "base_app.html" %}
{% block main-container %}
{% for unity in unities %}
	{{unity}}
{% endfor %}
{% endblock %}

templates/units/unitytype_form.html
{% extends "base.html" %}
{% load projects_tags %}
{% block title %}Agrega los tipos de unidad de tu proyecto{% endblock %}
{% block main-container %}
	<section id="main-container">
		<div class="container">
			<div class="row">
				<div class="col s12 welcome-title-wrapper hide-on-small-only">
					{% get_project project_slug as project %}
					<h1 class="welcome-title center">{{request.user.first_name}}, agrega los tipos de unidad que tendrá {{project}}</h1>
				</div>
				<div class="col s12 center">
					<div class="row">
				        <div class="col s12 m6 l4 push-m3 push-l4 creation-box-wrapper">
				          	<div class="card medium" style="height: 430px;">
				          	<!--<i class="material-icons add-project-icon">add_circle_outline</i>-->
					          	<div class="card-content" style="font-size: 18px; font-weight: bold; color: #6c7383;">
					              <p>Agrega un tipo de unidad para Villa Paraiso</p>
					           	</div>
					           	<form method="POST" id="create-unityype" action="{% url "unity_types_create" project.slug %}">
					           	{% csrf_token %}
						           	<div class="row">
						           			<!--Hardcoded form for Django CreateView-->
						           			{{form.errors}}
						           			<div class="col s8 m8 l8 offset-s2 offset-m2 offset-l2">
												<select class="browser-default" id="id_type_name" name="type_name">
													<option value="" disabled selected>Selecciona el tipo de unidad</option>
                                                    {% for value, key in form.fields.type_name.choices %}
                                                        <option value="{{value}}">{{key}}</option>
                                                    {% endfor %}
                                            	</select>
			        						</div>
			        						<div class="col s8 m8 l8 offset-s2 offset-m2 offset-l2">
												<select class="browser-default" id="id_unitytype_name" name="unitytype_name">
													<option value="" disabled selected>Selecciona el tipo</option>
                                                    {% for value, key in form.fields.unitytype_name.choices %}
                                                        <option value="{{value}}">{{key}}</option>
                                                    {% endfor %}
                                            	</select>
			        						</div>
			        						<div class="input-field col s4 m4 l4 offset-s2 offset-m2 offset-l2">
			        							<input id="id_private_area" maxlength="100" name="private_area" step="any" type="number"/>
			        							<label for="id_private_area" style="text-align: left;">Area privada:</label>
			        						</div>
			        						<div class="input-field col s4 m4 l4">
			        							<input id="id_built_area" maxlength="100" name="built_area" step="any" type="number"/>
			        							<label for="id_built_area" style="text-align: left;">Area construida:</label>
			        						</div>
			        						<div class="input-field col s4 m4 l4 offset-s2 offset-m2 offset-l2">
			        							<input id="id_bathrooms" maxlength="100" name="bathrooms" type="number"/>
			        							<label for="id_bathrooms" style="text-align: left;">Baños:</label>
			        						</div>
			        						<div class="input-field col s4 m4 l4">
			        							<input id="id_bedrooms" maxlength="100" name="bedrooms" type="number"/>
			        							<label for="id_bedrooms" style="text-align: left;">Habitaciones:</label>
			        						</div>
		      						</div>
						           	<button href="#" type="submit" class="waves-effect waves-light btn custom-btn"><i class="material-icons left" style="font-weight: bold;">add</i>Agregar</button>
						        </form>
				          	</div>
				        </div>
				        <!--
				        <div class="col s12 m6 l4 creation-box-wrapper">
				          	<div class="unitytype-addbtn">
					          	<div class="card-content" style="font-size: 14px; color: #6c7383;">
					          	<a id="add-unutytype" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
					             <p>Agregar otro tipo de unidad</p>
					           	</div>
				          	</div>
				        </div>
				        -->
      				</div>
				</div>
				<div class="col s12">
					<div class="row">
					<h2 style="font-size: 28px;">Tipos de unidad creados</h2>
					<div id="unitytypes-container">
						{% if unitytypes %}
							{% for unitytype in unitytypes %}
					        <div class="col s12 m6 l4 creation-box-wrapper">
					          	<div class="card medium">
					          	<!--<i class="material-icons add-project-icon">add_circle_outline</i>-->
						          	<div class="card-content center" style="font-size: 18px; font-weight: bold; color: #6c7383;">
						              <p>{{unitytype.get_type_name_display}} {{unitytype.get_unitytype_name_display}}</p>
						           	</div>

									  <ul class="collection">
									    <li class="collection-item avatar">
									      <i class="material-icons circle" style="background-color: #089CD3;">person_outline</i>
									      <p class="unitytype-info unitytype-legend">Area Privada</p>
									      <a href="#!" class="secondary-content unitytype-info">{{unitytype.private_area}} m2</a>
									    </li>
									    <li class="collection-item avatar">
									      <i class="material-icons circle" style="background-color: #FE8B4C;">location_city</i>
									      <p class="unitytype-info unitytype-legend">Area Construida</p>
									      <a href="#!" class="secondary-content unitytype-info">{{unitytype.built_area}} m2</a>
									    </li>
									    <li class="collection-item avatar">
									      <i class="material-icons circle" style="background-color: #61CC40;">airline_seat_legroom_normal</i>
									      <p class="unitytype-info unitytype-legend">Baños</p>
									      <a href="#!" class="secondary-content unitytype-info">{{unitytype.bathrooms}}</a>
									    </li>
									    <li class="collection-item avatar">
									      <i class="material-icons circle" style="background-color: #f35555;">hotel</i>
									      <p class="unitytype-info unitytype-legend">Habitaciones</p>
									      <a href="#!" class="secondary-content unitytype-info">{{unitytype.bedrooms}}</a>
									    </li>
									  </ul>
					          	</div>
					        </div>
					        {% endfor %}
				        {% endif %}
				        <div id="no-unytytype" class="col s12 m5 l4 creation-box-wrapper">
					          	<div class="next-unitytype">
					          	</div>
					        </div>
				        </div>
      				</div>
				</div>


			</div>
		</div>
	</section>

	<nav id="nav-bottom" class="nav-bottom">
    <div class="container">
        <div style="display: inline-block; float: right;">
          <a class="waves-effect waves-light btn custom-btn" href="{% url "unities_import" project_slug %}">Continuar</a>
        </div>
    </div>
  </nav>
{% endblock %}
{% block custom-js %}
<script language="JavaScript">
	function check_for_unytypes(){
		var a = $("#unitytypes-container").children().length;
        if (a > 1){
        	$("#nav-bottom").fadeIn(4000)
        }
        return true
	}
    $(document).ready(function() {
    	$("#nav-bottom").hide()
    	check_for_unytypes();
        $('#create-unityype').submit(function() { // catch the form's submit event
            $.ajax({ // create an AJAX call...
                data: $(this).serialize(), // get the form data
                type: $(this).attr('method'), // GET or POST
                url: $(this).attr('action'), // the file to call
                success: function(data) { // on success..
                    $('#create-unityype').trigger("reset");
                    if (data["pk"]){
                    	type_name = data["type_name"];
                    	unitytype_name = data["unitytype_name"]
                    	private_area = data["private_area"]
                    	built_area = data["built_area"]
                    	bathrooms = data["bathrooms"]
                    	bedrooms = data["bedrooms"]
                    	$('#unitytypes-container').prepend(
                    		"<div class='col s12 m6 l4 creation-box-wrapper'><div class='card medium'><div class='card-content center' style='font-size: 18px; font-weight: bold; color: #6c7383;'><p>" + type_name + " " + unitytype_name + "</p></div><ul class='collection'><li class='collection-item avatar'><i class='material-icons circle' style='background-color: #089CD3;'>person_outline</i><p class='unitytype-info unitytype-legend'>Area Privada</p><a href='#!' class='secondary-content unitytype-info'>" + private_area + " m2" + "</a></li><li class='collection-item avatar'><i class='material-icons circle' style='background-color: #FE8B4C;'>location_city</i><p class='unitytype-info unitytype-legend'>Area Construida</p><a href='#!' class='secondary-content unitytype-info'>" + built_area +" m2" +"</a></li><li class='collection-item avatar'><i class='material-icons circle' style='background-color: #61CC40;'>airline_seat_legroom_normal</i><p class='unitytype-info unitytype-legend'>Baños</p><a href='#!' class='secondary-content unitytype-info'>" + bathrooms + "</a></li><li class='collection-item avatar'><i class='material-icons circle' style='background-color: #f35555;'>hotel</i><p class='unitytype-info unitytype-legend'>Habitaciones</p><a href='#!' class='secondary-content unitytype-info'>" + bedrooms + "</a></li></ul></div></div>"
                    	).hide().fadeIn(2000);
                    	//$("#no-unytytype").hide()
                    	check_for_unytypes();
                    }
                },
                error: function (data) {
        			alert("There was a big error");
        			alert(data);
      			}
            });
            return false;
        });
    });
</script>
{% endblock %}